// <auto-generated/>
namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarBrands'
    public partial class CarBrands
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarBrands'
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Justification = "AutoGenerated")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.CarBrands()'
        public CarBrands()
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.CarBrands()'
        {
            this.CarModel = new HashSet<CarModels>();
        }
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.Id'
        public int Id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.Id'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.Name'
        public string Name { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.Name'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.Country'
        public string Country { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.Country'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.Url'
        public string Url { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.Url'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.Founded'
        public Nullable<System.DateTime> Founded { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.Founded'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.YearlyRevenue'
        public Nullable<int> YearlyRevenue { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.YearlyRevenue'
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Justification = "AutoGenerated")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.CarModel'
        public virtual ICollection<CarModels> CarModel { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarBrands.CarModel'
    }
}
