//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_brands'
    public partial class car_brands
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_brands'
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_brands.car_brands()'
        public car_brands()
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_brands.car_brands()'
        {
            this.car_models = new HashSet<car_models>();
        }
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_brands.id'
        public int id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_brands.id'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_brands.name'
        public string name { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_brands.name'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_brands.country'
        public string country { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_brands.country'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_brands.url'
        public string url { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_brands.url'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_brands.founded'
        public Nullable<System.DateTime> founded { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_brands.founded'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_brands.yearly_revenue'
        public Nullable<int> yearly_revenue { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_brands.yearly_revenue'
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_brands.car_models'
        public virtual ICollection<car_models> car_models { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_brands.car_models'
    }
}
