// <auto-generated/>
namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models'
    public partial class CarModels
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models'
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Justification = "AutoGenerated")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models.car_models()'
        public CarModels()
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models.car_models()'
        {
            this.model_extra_connection = new HashSet<ModelExtraConnection>();
        }
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models.id'
        public int id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models.id'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models.brand_id'
        public int brand_id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models.brand_id'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models.name'
        public string name { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models.name'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models.production_start'
        public Nullable<System.DateTime> production_start { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models.production_start'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models.engine_size'
        public Nullable<int> engine_size { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models.engine_size'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models.horsepower'
        public Nullable<int> horsepower { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models.horsepower'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models.starting_price'
        public Nullable<int> starting_price { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models.starting_price'
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models.car_brands'
        public virtual CarBrands car_brands { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models.car_brands'
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Justification = "AutoGenerated")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'car_models.model_extra_connection'
        public virtual ICollection<ModelExtraConnection> model_extra_connection { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'car_models.model_extra_connection'
    }
}
