//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarShopDBaseEntities : DbContext
    {
        public CarShopDBaseEntities()
            : base("name=CarShopDBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car_brands> car_brands { get; set; }
        public virtual DbSet<car_models> car_models { get; set; }
        public virtual DbSet<extra> extras { get; set; }
        public virtual DbSet<model_extra_connection> model_extra_connection { get; set; }
    }
}
