//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities'
    public partial class CarShopDBaseEntities : DbContext
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities'
    {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.CarShopDBaseEntities()'
        public CarShopDBaseEntities()
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.CarShopDBaseEntities()'
            : base("name=CarShopDBaseEntities")
        {
        }
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.OnModelCreating(DbModelBuilder)'
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.OnModelCreating(DbModelBuilder)'
        {
            throw new UnintentionalCodeFirstException();
        }
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.car_brands'
        public virtual DbSet<car_brands> car_brands { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.car_brands'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.car_models'
        public virtual DbSet<car_models> car_models { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.car_models'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.extras'
        public virtual DbSet<extra> extras { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.extras'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.model_extra_connection'
        public virtual DbSet<model_extra_connection> model_extra_connection { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'CarShopDBaseEntities.model_extra_connection'
    }
}
