//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra'
    public partial class extra
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra'
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.extra()'
        public extra()
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.extra()'
        {
            this.model_extra_connection = new HashSet<model_extra_connection>();
        }
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.id'
        public int id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.id'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.category_name'
        public string category_name { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.category_name'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.name'
        public string name { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.name'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.price'
        public Nullable<int> price { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.price'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.color'
        public string color { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.color'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.reuseable'
        public Nullable<byte> reuseable { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.reuseable'
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.model_extra_connection'
        public virtual ICollection<model_extra_connection> model_extra_connection { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.model_extra_connection'
    }
}
