//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class extra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public extra()
        {
            this.model_extra_connection = new HashSet<model_extra_connection>();
        }
    
        public int id { get; set; }
        public string category_name { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public string color { get; set; }
        public Nullable<byte> reuseable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<model_extra_connection> model_extra_connection { get; set; }
    }
}
