// <auto-generated/>
namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra'
    public partial class Extras
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra'
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Justification ="AutoGenerated")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.extra()'
        public Extras()
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.extra()'
        {
            this.model_extra_connection = new HashSet<ModelExtraConnection>();
        }
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.id'
        public int id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.id'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.category_name'
        public string category_name { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.category_name'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.name'
        public string name { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.name'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.price'
        public Nullable<int> price { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.price'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.color'
        public string color { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.color'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.reuseable'
        public Nullable<byte> reuseable { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.reuseable'

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "model", Justification = "AutoGenerated")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "connection", Justification = "AutoGenerated")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "extra", Justification = "AutoGenerated")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Justification = "AutoGenerated")]
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'extra.model_extra_connection'
        public virtual ICollection<ModelExtraConnection> model_extra_connection { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'extra.model_extra_connection'
    }
}
