//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class model_extra_connection
    {
        public int id { get; set; }
        public int model_id { get; set; }
        public int extra_id { get; set; }
    
        public virtual car_models car_models { get; set; }
        public virtual extra extra { get; set; }
    }
}
