//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection'
    public partial class model_extra_connection
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection'
    {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection.id'
        public int id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection.id'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection.model_id'
        public int model_id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection.model_id'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection.extra_id'
        public int extra_id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection.extra_id'
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection.car_models'
        public virtual car_models car_models { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection.car_models'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection.extra'
        public virtual extra extra { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'model_extra_connection.extra'
    }
}
