// <auto-generated/>
namespace CarShop.Data
{
    using System;
    using System.Collections.Generic;
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection'
    public partial class ModelExtraConnection
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection'
    {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection.Id'
        public int Id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection.Id'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection.ModelId'
        public int ModelId { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection.ModelId'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection.ExtraId'
        public int ExtraId { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection.ExtraId'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection.CarModel'
        public virtual CarModels CarModel { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection.CarModel'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection.Extra'
        public virtual Extras Extra { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'ModelExtraConnection.Extra'
    }
}
